# Generated by Django 5.1.1 on 2024-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_video_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="rating",
        ),
    ]
