# Generated by Django 5.1.1 on 2024-09-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_video_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="image_product",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
