# Generated by Django 5.1.1 on 2024-09-24 06:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_video_image_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="image_product",
        ),
    ]
