# Generated by Django 5.1.1 on 2024-10-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_video_image_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video_thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
