# Generated by Django 5.1.1 on 2024-11-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_video_video_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_thumbnail",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
