# Generated by Django 5.1.1 on 2024-11-19 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_video_video_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="release_date",
        ),
    ]
