# Generated by Django 5.1.1 on 2024-11-19 23:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_remove_video_release_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="release_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
